name: evaluacion_docente_frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  auth0_flutter: 1.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  google_fonts: ^4.0.3
  flutter_inappwebview: ^5.3.2 
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.1.0
  test: ^1.16.5


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
